name: chat_with_video_final
description: Chat with video example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  stream_chat_flutter: ^6.8.1
  stream_video_flutter: 0.0.3
  envied: ^0.3.0

dependency_overrides:
  rate_limiter: ^1.0.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
